version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-container
    volumes:
      - .:/var/www/html
    ports:
      - 8000:80
    networks:
      - laravel-network
