Version: '3.3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-container
    volumes:
      - .:/var/www/html
    ports:
      - 80:80
    networks:
      - laravel-network
  nginx:
    image: nginx:latest
    container_name: my-laravel-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel-network      
networks:
  laravel-network:
    driver: bridge
